/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PrivatePropertyListing = IDL.Record({
  'latitude' : IDL.Float64,
  'title' : IDL.Text,
  'ownerName' : IDL.Text,
  'propertyType' : IDL.Text,
  'ownerPhone' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'priceRange' : IDL.Text,
  'longitude' : IDL.Float64,
  'areaName' : IDL.Text,
  'fullAddress' : IDL.Text,
  'photos' : IDL.Vec(ExternalBlob),
});
export const PaymentRecord = IDL.Record({
  'propertyId' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
  'transactionId' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PublicPropertyListing = IDL.Record({
  'title' : IDL.Text,
  'propertyType' : IDL.Text,
  'isActive' : IDL.Bool,
  'priceRange' : IDL.Text,
  'areaName' : IDL.Text,
  'photos' : IDL.Vec(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProperty' : IDL.Func(
      [IDL.Text, PrivatePropertyListing],
      [],
      [],
    ),
  'deleteProperty' : IDL.Func([IDL.Text], [], []),
  'getAllPaymentRecords' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(PaymentRecord)))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPropertyDetails' : IDL.Func(
      [IDL.Text],
      [PrivatePropertyListing],
      ['query'],
    ),
  'getPublicProperties' : IDL.Func(
      [],
      [IDL.Vec(PublicPropertyListing)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitPayment' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PrivatePropertyListing = IDL.Record({
    'latitude' : IDL.Float64,
    'title' : IDL.Text,
    'ownerName' : IDL.Text,
    'propertyType' : IDL.Text,
    'ownerPhone' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'priceRange' : IDL.Text,
    'longitude' : IDL.Float64,
    'areaName' : IDL.Text,
    'fullAddress' : IDL.Text,
    'photos' : IDL.Vec(ExternalBlob),
  });
  const PaymentRecord = IDL.Record({
    'propertyId' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
    'transactionId' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PublicPropertyListing = IDL.Record({
    'title' : IDL.Text,
    'propertyType' : IDL.Text,
    'isActive' : IDL.Bool,
    'priceRange' : IDL.Text,
    'areaName' : IDL.Text,
    'photos' : IDL.Vec(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProperty' : IDL.Func(
        [IDL.Text, PrivatePropertyListing],
        [],
        [],
      ),
    'deleteProperty' : IDL.Func([IDL.Text], [], []),
    'getAllPaymentRecords' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(PaymentRecord)))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPropertyDetails' : IDL.Func(
        [IDL.Text],
        [PrivatePropertyListing],
        ['query'],
      ),
    'getPublicProperties' : IDL.Func(
        [],
        [IDL.Vec(PublicPropertyListing)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitPayment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };